Makefile's users-integration-test depends on $(PROTO_GOS).
Fixes issues like:
```
make: Entering directory '/go/src/github.com/weaveworks/service'
mockgen -destination=billing-api/db/mock_db/mock_db.go github.com/weaveworks/service/billing-api/db DB
../common/billing/grpc/client.go:14:2: undefined: BillingClient
../common/billing/grpc/client.go:20:9: undefined: BillingClient
```
See: https://circleci.com/gh/weaveworks/service/7611

Before this commit, this is reproducible locally by running:
```
$ make clean ; rm common/billing/grpc/billing.pb.go ; make users-integration-test
```