Run flux-api integration tests against postgres
The motivation behind this change was automatically cleaning up the temporary
files generated in running `make flux-nats-tests`. Considering we're already
spinning up a NATS container, I figured we can throw in postgres too.

None of our environments - local, dev, or prod - use anything other than
postgres for history storage, and it turns out the `ql` database doesn't behave
identically to that.

Specifically, the non-postgres option allows an event lacking `EndedAt` to be
written, whereas postgres does not, instead failing with:

```
--- FAIL: TestFluxsvc_History (0.09s)
        main_test.go:327: executing HTTP request: logging event: pq: null value in column "ended_at" violates not-null constraint
```